### ISSUE TITLE
Could not load file or assembly ... or one of its dependencies. The parameter is incorrect

### ISSUE THREAD

**Issue by chuongmep** [chuongmep/RevitAddInManager#10] opened 2022-01-26 08:45 UTC
**Describe the bug**
Could not load file or assembly 'RoslynPad.Roslyn, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
- Problem cause when we load a dll depend on multiple assembly other.

**To Reproduce**
- Load Assembly using reference to other assembly
- Run to see error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31106432/151130903-860330ce-5cc0-4d8c-abd0-d77ecb382cd7.png)
![image](https://user-images.githubusercontent.com/31106432/151131008-8be95bdd-2c40-4502-aa4c-54d128e9e87b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Revit 2022
**Additional context**

**Comment by chuongmep** [comment] 2022-01-31 02:45
the problem has been temporarily fixed but still happens at some point in time, needs further investigation to fully resolve

**Comment by syncltu** [comment] 2022-05-28 14:35
Good day. Thanks for Your contribution to the community. Is it only me or i.e. Automapper or Autofac container nuget packages does not load as well and throws "Could not load file or assembly. The located assembly's manifest definition does not match the assembly reference.". If you launch through Revit panel interface, it works without problems. When you launch addin manager tool, it crashes.

**Comment by chuongmep** [comment] 2022-05-28 14:38
@syncltu you have any github project sample to i can create again this pepblem ?

**Comment by syncltu** [comment] 2022-05-28 15:45
Well, I tried to create a small sample project, and guess what... It worked! Then on the original project that I was having issues, I cleared all cache, deleted all folders from temp that Addin Manager generates and it also magically worked. I guess the problem will occur once again anytime soon, but at the meantime I cannot reproduce the issue. Probably there is something wrong with my project, not with Addin Manager itself. Sorry for bothering

**Comment by chuongmep** [comment] 2022-05-28 15:50
No problem, if issue still cause please report again , hope can help to project become better 😉

**Comment by pierrenavarra** [comment] 2022-07-20 14:44
Hi,
Does the pb is still here?
I'm try to explain my pb : 
I create 2 projects into a solution.
One HelloWorld with an ExternalCommand.
Into the other, just a simple class to show a Dialog
So, In HellWorld  project, i've got the Display reference added 
When I compile, and putting two dlls and loading them threw .addin in Revit, it works
But, When I Load with AIM, I've got an error. 
Do you know what?
![screenshot_181](https://user-images.githubusercontent.com/54843266/180007006-7ad7c43d-b14c-4dd4-9ef8-eeaa0b2bc20b.png)

**Comment by chuongmep** [comment] 2022-07-21 00:41
Hi @pierrenavarra,
You have any project demo sample like this in GitHub ?

**Comment by pierrenavarra** [comment] 2022-07-21 14:28
Hi @chuongmep 

Thx for answering me.
For exemple, I've followed Marko Koljancic's tutorial
You can download this sample demo : I've got an error in AIM when I try to use ess_routing project
But, if I transpose all function I wrote in ess_routing.core project into ess_routing project, it works....
It's strange...
Have a look into this vidéo...
[https://youtu.be/lQPfp_5YLSg](url)

**Comment by syncltu** [comment] 2022-07-21 19:36
@pierrenavarra  Hello, Im having the same issue from time to time. What you can do is to debug and find which package it fails to load. For me it usually was failing to load nuget packages. What usually helps for me:
1. Start command through revit interface, button and then in the same revit session opening it through addin manager.
2. Deleting all folders that are created in "temp" data of user folder. These are created when addin manager is launched

**Comment by pierrenavarra** [comment] 2022-07-22 06:20
thx answering @syncltu 
1. I do that : start command through revit and through AIM in the same sessions.
2. I've allready deleting temp directory of AIM
I do not have packages....

**Comment by chuongmep** [comment] 2022-07-22 06:21
@pierrenavarra please upload a project demo on github, I will review detail for you.

**Comment by pierrenavarra** [comment] 2022-07-22 06:22
Hi @chuongmep 
I've posted a ess_routing.zip into my precedent post...https://github.com/chuongmep/RevitAddInManager/issues/10#issuecomment-1191555222

**Comment by chuongmep** [comment] 2022-07-22 06:28
> 
Let me check for you.

**Comment by pierrenavarra** [comment] 2022-07-25 06:38
Hi @chuongmep 
Do you have news for me :-)

**Comment by chuongmep** [comment] 2022-07-25 07:40
> Hi @chuongmep Do you have news for me :-)
 Hi @pierrenavarra, still not yet, I'm in still in process receive new job so busy. I will review when I have computer.

**Comment by pierrenavarra** [comment] 2022-07-25 08:42
Hi @chuongmep
Thx no panic!

**Comment by chuongmep** [comment] 2022-08-24 13:57
> Tested but can't create again this error.

**Comment by syncltu** [comment] 2022-08-24 19:08
Some more insights. If visual studio solution contains of multiple projects, it tends to fail to load some of the nuget packages whenever you rebuild without closing. One thing that helped me is making a variable assembly version, what it means is that whenever you build, your assemblies version increments by 1 everytime. Because of this, addin manager loads newer assemblies without a problem. Take a look if it helps
![image](https://user-images.githubusercontent.com/38985094/186502558-955a6940-887b-4d0b-bb2c-763d194ef872.png)
Note that shared assembly info is a linked file and is the same for multiple projects. When you build a release you can create a normal version however you want, 1.0.0 or whatever. * symbol makes it variable. @pierrenavarra  @chuongmep

**Comment by syncltu** [comment] 2022-08-24 19:10
For all my colleagues and me this fixed the issue, should help you hopefully

**Comment by pierrenavarra** [comment] 2022-08-25 07:13
> > Tested but can't create again this error. @pierrenavarra,

Oh, thx @chuongmep

**Closed** 2023-09-20 08:18 UTC
Labels: bug
